Add source angular -- luu y file package.json node_modules/rxjs/internal/types.d.ts(81,44): error TS1005: ';' expected error after installation of Angular 6
This problem might arise due to version mismatch. To solve your problem you need to do following changes in your package.json file.
Step 1 : Go to package.json and modify "rxjs": "^6.0.0" to "rxjs": "6.0.0"
Step 2 Run npm update in your project.
There is no need to change the typescript version. (Mine: "typescript": "~2.7.2")
Edit: If you are using rxjs-compat then you also need to do following in order to fixed the issue. change the rxjs-compat version from "rxjs-compat": "^6.2.2" to "rxjs-compat": "6.2.2"
Hope this will help!